# Generated by Django 5.0.4 on 2024-05-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="details",
            field=models.TextField(default=""),
        ),
    ]
