# Generated by Django 5.0.4 on 2024-06-11 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_cart_cartitem_cart_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
